# Generated by Django 3.2.7 on 2021-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaddyAreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('growth_calssification', models.IntegerField()),
                ('paddy_images', models.ImageField(blank=True, default='default.png', upload_to='info_images')),
            ],
        ),
    ]
