# Generated by Django 3.2.7 on 2021-12-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddyareainfo',
            old_name='name',
            new_name='area_name',
        ),
        migrations.RemoveField(
            model_name='paddyareainfo',
            name='growth_calssification',
        ),
        migrations.RemoveField(
            model_name='paddyareainfo',
            name='paddy_images',
        ),
        migrations.AddField(
            model_name='paddyareainfo',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='paddyareainfo',
            name='logitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='paddyareainfo',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ImagePredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='photos/%Y/%m/%d')),
                ('prediction', models.IntegerField()),
                ('paddy_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paddyareainfo')),
            ],
        ),
    ]
